/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SimpleJadwal;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;
/**
 *
 * @author hecke
 */
public class ScheduleTable extends javax.swing.JFrame {

    private JTable table;
    private DefaultTableModel tableModel;

    public ScheduleTable(ArrayList<Schedule> scheduleList) {
        // Judul JFrame
        setTitle("Hasil Jadwal Anda");
        setSize(600, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());

        // Label Judul
        JLabel titleLabel = new JLabel("Hasil Jadwal Anda", SwingConstants.CENTER);
        titleLabel.setFont(new Font("Arial", Font.BOLD, 18));
        titleLabel.setOpaque(true);
        titleLabel.setBackground(Color.LIGHT_GRAY);
        add(titleLabel, BorderLayout.NORTH);

        // Model Tabel
        String[] columnNames = {"Nama Kegiatan", "Hari", "Tanggal", "Keterangan Tambahan"};
        tableModel = new DefaultTableModel(columnNames, 0);
        table = new JTable(tableModel);
        JScrollPane scrollPane = new JScrollPane(table);
        add(scrollPane, BorderLayout.CENTER);

        // Mengisi data ke tabel
        for (Schedule schedule : scheduleList) {
            Object[] rowData = {
                schedule.getActivityName(),
                schedule.getDay(),
                schedule.getDate(),
                schedule.getAdditionalInfo()
            };
            tableModel.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
// Test dummy data (hapus sebelum implementasi)
        ArrayList<Schedule> dummyData = new ArrayList<>();
        dummyData.add(new Schedule("Belajar Java", "Senin", "01/01/2024", "Minggu Pertama"));
        dummyData.add(new Schedule("Meeting", "Selasa", "02/01/2024", "Penting"));

        new ScheduleTable(dummyData).setVisible(true);
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
